ebay:
  marketplaceId: EBAY_US
  httpTimeOutMs: 60000
retry:
  maxRetries: 3
  backoffInterval: 1000
spring:
  config:
    activate:
      on-profile: LOCAL
      server:
        scheme: http
        host: localhost
        port: 8080
