ebay:
  marketplaceId: EBAY_US
  httpTimeOutMs: 60000
  maxRetries: 3
  backoffInterval: 1000
  resourceMap:
    payment_policy: sell/account/v1/payment_policy
  spring:
    config:
      activate:
        on-profile: LOCAL
        server:
          scheme: http
          host: localhost
          port: 8080
